name: fileconverter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  image: ^4.1.3
  pdf: ^3.10.4
  printing: ^5.12.0
  share_plus: ^7.2.1
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.1.10
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.1.0
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1
  animations: ^2.0.8 
  syncfusion_flutter_pdf: ^24.2.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

  assets:
    - assets/icons/
    - assets/fonts/

        
dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master
